graph TD

    %% -------------------- SDR  --------------------
    subgraph SDR_Clone
        VCC_3V3 --> MODEM["AT86RF215 Modem"]
        VCC_3V3 --> MIXER["RFFC5072 Mixer"]
        GND --> MODEM
        GND --> MIXER

        MODEM --> RF_SUB1G["RF Front-End Sub-1GHz"]
        MIXER --> RF_6GHz["RF Front-End 30MHz-6GHz"]
        RF_SUB1G --> SMA_SUB1G["SMA Connector Sub-1GHz"]
        RF_6GHz --> SMA_6GHz["SMA Connector 30MHz-6GHz"]

        TCXO["TCXO 26MHz"] --> MODEM
        TCXO --> MIXER
        VCC_3V3 --> TCXO
        GND --> TCXO
        EXT_CLK["External REF IN"] --> MIXER

        PMOD["PMOD Header 12p"]
        VCC_3V3 --> PMOD
        GND --> PMOD

        LED_STATUS["RF Activity LEDs"]
        LED_STATUS -->|330Ω| GND

        USER_SW["User Switch"]

        GPIO_STM32["STM32 GPIO"]
    end


    %% -------------------- NFC & IR --------------------
    subgraph NFC_IR
        STM32 -->|I2C| PN532_I2C["I2C PN532"]
        PN532_I2C --> PN532["Módulo NFC PN532"]
        PN532 --> LOOP_ANT["NFC Ant Loop"]
        VCC_3V3 --> PN532
        GND --> PN532

        STM32 -->|GPIO| IR_TX["GPIO IR TX"]
        IR_TX --> R_IR["Resistor 33Ω"]
        R_IR --> IR_EMITTER["TSAL6200 Emitter"]
        IR_EMITTER --> GND

        IR_RX["VS1838B IR RX"] -->|GPIO| STM32
        IR_RX --> R_PULLUP["Pull-up 10kΩ"]
        R_PULLUP --> VCC_3V3
        IR_RX --> C_IR["Capacitor 100nF"]
        C_IR --> GND
        VCC_3V3 --> IR_RX
    end

    %% -------------------- EEPROM --------------------
    subgraph EEPROM_Block
        EEPROM_CHIP["RPi-HAT EEPROM"] -->|I2C| STM32
        VCC_3V3 --> EEPROM_CHIP
        GND --> EEPROM_CHIP
    end
